lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list, get_page_data_by_page_number, get_friend_data

urlpatterns = [
     url(r'^$', index, name='index'),
     url(r'^add-friend/$', add_friend, name='add-friend'),
     url(r'^validate-npm/$', validate_npm, name='validate-npm'),
     url(r'^delete-friend/$', delete_friend, name='delete-friend'),
     url(r'^get-friend-data/$', get_friend_data, name='get-friend-data'),
     url(r'^get-friend-list/$', friend_list, name='get-friend-list'),
     url(r'^get-students-by-page/(?P<page_number>[0-9]+)/$', get_page_data_by_page_number)
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
from lab_1.views import index as index_lab1
from lab_2.views import index as index_baru
from lab_4.views import index as index_baru2

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4,namespace='lab-4')),
    url(r'^lab-5/', include(lab_5,namespace='lab-5')),
    url(r'^lab-6/', include(lab_6,namespace='lab-6')),
    url(r'^lab-7/', include(lab_7,namespace='lab-7')),
    url(r'^$', index_baru2, name='index')
]

lab_7/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250, unique=True)
    added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseBadRequest, QueryDict
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {}
csui_helper = CSUIhelper()

def index(request):
    mahasiswa_list, next_page, prev_page = csui_helper.instance.get_mahasiswa_list()
    friend_list = Friend.objects.all()

    response = {
        "mahasiswa_list": mahasiswa_list,
        "friend_list": friend_list,
        "next_page_num": next_page,
        "prev_page_num": prev_page,
    }

    response['author'] = 'Mohammad Raffi Akbar'
    html = 'lab_7/lab_7.html'
    return render(request, html, response)

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)

def friend_list_json(request): # update
    friends = [obj.as_dict() for obj in Friend.objects.all()]
    return JsonResponse({"results": friends}, content_type='application/json')

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']

        try:
            db_data = Friend.objects.get(npm=npm)
            return HttpResponseBadRequest()
        except Friend.DoesNotExist:
            friend = Friend(friend_name=name, npm=npm)
            friend.save()
            data = model_to_dict(friend)
            return HttpResponse(data)

@csrf_exempt
def delete_friend(request):
    if request.method == "POST":
        pk = request.POST['id']
        Friend.objects.filter(pk=pk).delete()
        return HttpResponse('Ok')
    return HttpResponseBadRequest()

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    data = {
        'is_taken': Friend.objects.filter(npm=npm).exists()
    }
    return JsonResponse(data)

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

def get_page_data_by_page_number(request, page_number):
    mahasiswa_list, next_page, prev_page = csui_helper.instance.get_mahasiswa_list_by_page(page_number)
    data = {
        "mahasiswa_list": mahasiswa_list,
        "next_page_num": next_page,
        "prev_page_num": prev_page,
    }
    return JsonResponse(data)

def get_friend_data(request):
    data = serializers.serialize('json', Friend.objects.all())
    struct = json.loads(data)

    data = []
    for instance in struct:
        obj = {
            'id': instance['pk'],
            'data': instance['fields']
        }

        data.append(obj)
    return JsonResponse({"data":data})

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> friend Fasilkom</h2>
                    <div id="friend-list" class="list-group">

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        $( document ).ready(function () {
            $.ajax({
                method: "GET",
                url: "{% url 'lab-7:get-friend-data' %}",
                dataType: 'json',
                success: function (response) {
                    html = '';

                    response.data.forEach(function(element) {
                        html += '<a class="list-group-item clearfix">' +
                                    element.data.friend_name + ' (' + element.data.npm + ')' +
                                    '<span class="pull-right">' +
                                        '<span class="btn btn-xs btn-default" onclick="deleteFriend(this, ' + element.id + ')">Hapus teman</span>' +
                                    '</span>' +
                                '</a>'
                    });

                    $("#friend-list").append(html);
                },
                error: function(error){
                    alert('error')
                }
            });
        });

        var deleteFriend = function(caller, id) {
            $.ajax({
                method: "POST",
                url: '{% url "lab-7:delete-friend" %}',
                data: {id: id},
                success: function(response) {
                    console.log(response);
                    $(caller.parentNode.parentNode).remove();
                    alert('Berhasil menghapus dari pertemanan!')
                },
                error: function(error) {
                    console.log(error);
                }
            });
        }

    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list">
    <div class="container">
      <button class="btn btn-primary" id="prev-page">< Prev</button>
      <button class="btn btn-primary" id="next-page">Next ></button>
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group" id="mahasiswa-list">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                                    <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                                        Tambah sebagai teman
                                    </span>
                                </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>

</section>
{% endblock %}

{% block javascript %}
<script>
    nextPageUrl = "{{ next_page_num }}";
    prevPageUrl = "{{ prev_page_num }}";

    var addFriend = function(nama, npm) {
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:add-friend" %}',
            data: { name: nama, npm: npm},
            success : function (friend) {
                friend = JSON.parse(friend);
                html = '<a class="list-group-item clearfix">' +
                    friend.friend_name + ' (' + friend.npm + ')' +
                    '</a>';
                $("#friend-list").append(html);
                alert("Berhasil menambahkan teman!")
            },
            error : function (error) {
                console.log(error);
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });
    };

    $("#add-friend").on("submit", function () {
        name = $("#field_name").val()
        npm = $("#field_npm").val()
        addFriend(name, npm);

        $("#field_name").val('');
        $("#field_npm").val('');

        event.preventDefault();
    });

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });

    $("#prev-page").on("click", function() {
        console.log('button prev pressed');
        var prevNumPage = prevPageUrl;
        console.log(prevPageUrl);

        if (prevNumPage) {
            console.log("will initiate the ajax call");
            $.ajax({
                method: "GET",
                url: "/lab-7/get-students-by-page/" + prevNumPage,
                dataType: "json",
                success: function (data) {
                    changePageComponents(data.mahasiswa_list, data.prev_page_num, data.next_page_num);
                }
            });
        }
    });

    $("#next-page").on("click", function() {
        console.log('button next pressed');
        var nextNumPage = nextPageUrl;
        console.log(nextPageUrl);

        if (nextNumPage) {
            console.log("will initiate the ajax call");
            $.ajax({
                method: "GET",
                url: "/lab-7/get-students-by-page/" + nextNumPage,
                dataType: "json",
                success: function (data) {
                    changePageComponents(data.mahasiswa_list, data.prev_page_num, data.next_page_num);
                }
            });
        }
    });

    var getUrlParameter = function getUrlParameter(urlTarget, sParam) {
        // window.location.search.substring(1)
        var sPageURL = decodeURIComponent(urlTarget),
            sURLVariables = sPageURL.split('&'),
            sParameterName,
            i;

        for (i = 0; i < sURLVariables.length; i++) {
            sParameterName = sURLVariables[i].split('=');

            if (sParameterName[0] === sParam) {
                return sParameterName[1] === undefined ? true : sParameterName[1];
            }
        }
    };

    var changePageComponents = function changePageComponents(mahasiswaList, prevUrl, nextUrl) {
        $("#mahasiswa-list").empty();
        prevPageUrl = prevUrl;
        nextPageUrl = nextUrl;

        var html = '';
        mahasiswaList.forEach(function(element) {
            html += '<a class="list-group-item clearfix">' +
                    element.nama + " (" + element.npm + ")" +
                    '<span class="pull-right">' +
                    '<span class="btn btn-xs btn-default" onClick="addFriend('+
                    "'" + element.nama + "'" + ',' + "'" + element.npm + "'" + ')">' +
                    'Tambah sebagai teman</span>' +
                    '</span>' +
                    '</a>';
        });
        $("#mahasiswa-list").append(html);
    }

</script>
{% endblock %}